### PR TITLE
migrate "status" and "repeater" fields

### LINKED ISSUE #20: Choices lost during migration
I have collections that feature muliple choice state selection, as seen in the V8 screenshots. The migration completed successfully but the choices are lost.

**V8**
Edit item:
grafik
Field configuration:
grafik

**V9**
Edit item:
grafik
Field configuration:
grafik

### PR DESCRIPTION
**Pull request by bywo**
resolves #20 and #22

### CODE REVIEW

**Comment by benhaynes** [comment]
Thank you, @bywo!!

**Comment by rijkvanzanten** [comment]
Thanks @bywo! Would you be able to do the same `status` trick for `dropdown` interfaces?

**Comment by bywo** [comment]
@rijkvanzanten alright, ready for another look!

**Review by rijkvanzanten — APPROVED** [review]
This is great! Thanks 🙂

**Pull request merged**
